### ISSUE TITLE
TRex crash issue in ASTF mode

### ISSUE THREAD

**Issue by egwakim** [cisco-system-traffic-generator/trex-core#1038]
Hi,
During traffic with ASTF mode, TRex server crashed with following error messages.
Can you check the issue?

Here is GDB trace messages 

1. Console messages
terminate called after throwing an instance of 'Json::LogicError'
  what():  in Json::Value::resolveReference(key, end): requires objectValue
./t-rex-64: line 106: 53899 Aborted                 (core dumped) ./_$(basename $0) $INPUT_ARGS $EXTRA_INPUT_ARGS

2. GDB traces
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fedc14ff700 (LWP 53930))]
(gdb) t a a bt full

Thread 1 (Thread 0x7fedc14ff700 (LWP 53930)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 163208757251, 140659127210080, 81604378626, 0, 
            140659127210264, 0, 0, 8019849059075322698, 8245935277854648679, 
            140659127213312, 140659127213360, 140659127213560, 0, 
            140659127213576, 0}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fedc3a6b7f1 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {
            sa_handler = 0x7fedc3e17680 <_IO_2_1_stderr_>, 
            sa_sigaction = 0x7fedc3e17680 <_IO_2_1_stderr_>}, sa_mask = {
            __val = {140659166765405, 64, 140659170309760, 3432, 1, 
              140659170309891, 140659166772993, 11, 140659170309760, 10, 
              140658434130192, 140659127212000, 37339152, 0, 140659166774195, 
              140659170309760}}, sa_flags = -1002047184, 
          sa_restorer = 0x7fedac002440}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00007fedc446270d in ?? ()
No symbol table info available.
#3  0x00007fedac002418 in ?? ()
No symbol table info available.
#4  0x00000000c4460890 in ?? ()
No symbol table info available.
#5  0x00007fedac0023f0 in ?? ()
No symbol table info available.
#6  0x0000000000bfb5d8 in ?? ()
No symbol table info available.
#7  0x00000000006e1420 in ?? ()
No symbol table info available.
#8  0x00007fedc44606d6 in ?? ()
No symbol table info available.
#9  0x00007fedac0023f0 in ?? ()
No symbol table info available.
#10 0x00007fedc4460721 in ?? ()
No symbol table info available.
#11 0x0000000000000330 in ?? ()
No symbol table info available.
#12 0x00007fedc4460939 in ?? ()
No symbol table info available.
#13 0x00007fedac002410 in ?? ()
No symbol table info available.
#14 0x00007fedc14fd7e0 in ?? ()
No symbol table info available.
#15 0x00007fed4da0da70 in ?? ()
No symbol table info available.
#16 0x00000000006cce2a in Json::throwLogicError (msg=...)
    at ../../../../trex-core/external_libs/json/jsoncpp.cpp:2683
No locals.
#17 0x00000000006dbb74 in Json::Value::resolveReference (this=0x7fed98004110, 
    this@entry=0x7fed4da0da70, key=key@entry=0xc02444 "layer_cfg", 
   cend=<optimized out>)
    at ../../../../trex-core/external_libs/json/jsoncpp.cpp:3545
        oss = <incomplete type>
        actualKey = {
          cstr_ = 0x7fedac000f60 "in Json::Value::resolveReference(key, end): requires objectValue", {index_ = 64, storage_ = {policy_ = 0, length_ = 16}}}
        it = <optimized out>
        defaultValue = {first = {
            cstr_ = 0x11b9a60 <vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@@GLIBCXX_3.4.21+24> "p\"N\304\355\177", {index_ = 18587992, storage_ = {policy_ = 0, length_ = 4646998}}}, 
          second = {static null = @0x1873880, static nullRef = @0x1873880, 
            static minLargestInt = -9223372036854775808, 
            static maxLargestInt = 9223372036854775807, 
            static maxLargestUInt = 18446744073709551615, 
            static minInt = -2147483648, static maxInt = 2147483647, 
            static maxUInt = 4294967295, 
            static minInt64 = -9223372036854775808, 
            static maxInt64 = 9223372036854775807, 
            static maxUInt64 = 18446744073709551615, value_ = {
              int_ = 140658769666433, uint_ = 140658769666433, 
              real_ = 6.9494665878481359e-310, bool_ = 129, 
              string_ = 0x7fedac002181 "n Json::Value::resolveReference(key, end): requires objectValue", map_ = 0x7fedac002181}, type_ = 129, allocated_ = 1, 
            comments_ = 0x7fedac002181, start_ = 140658769666432, 
            limit_ = 140658769666496}}
        value = <optimized out>
#18 0x00000000006dbbe9 in Json::Value::operator[] (
    this=this@entry=0x7fed4da0da70, key=key@entry=0xc02444 "layer_cfg")
    at ../../../../trex-core/external_libs/json/jsoncpp.cpp:3594
No locals.
#19 0x000000000073177b in CStackBase::attr_to_json (this=0x239c010, res=...)
    at ../../../../trex-core/src/stx/common/trex_stack_base.cpp:307
        __PRETTY_FUNCTION__ = "virtual void CStackBase::attr_to_json(Json::Value&)"
        cfg = <optimized out>
#20 0x00000000007038f1 in TrexPortAttrToJson::handle (this=0x7fed5c9a1910, 
    rx_core=<optimized out>)
    at ../../../../trex-core/src/stx/common/trex_messaging.cpp:314
No locals.
#21 0x0000000000720493 in CRxCore::handle_cp_msg (msg=0x7fed5c9a1910, 
    this=0x2363320)
    at ../../../../trex-core/src/stx/common/trex_rx_core.cpp:243
No locals.
#22 CRxCore::periodic_check_for_cp_messages (this=0x2363320)
    at ../../../../trex-core/src/stx/common/trex_rx_core.cpp:270
       node = 0x7fed5c9a1910
        msg = 0x7fed5c9a1910
        this = 0x2363320
        node = <optimized out>
        msg = <optimized out>
#23 0x00000000007229ee in CRxCore::work_tick (this=this@entry=0x2363320)
    at ../../../../trex-core/src/stx/common/trex_rx_core.cpp:439
        did_something = false
        pkt_cnt = <optimized out>
        limit = <optimized out>
        now = 8882.3910327366666
        DP_MSG_ITERATIONS = 10 '\n'
#24 0x00000000007e2c7e in CRxAstfCore::work_tick (this=0x2363320)
    at ../../../../trex-core/src/stx/astf/trex_astf_rx_core.cpp:209
        did_something = <optimized out>
        did_something = <optimized out>
#25 CRxAstfCore::do_background (this=0x2363320)
    at ../../../../trex-core/src/stx/astf/trex_astf_rx_core.cpp:99
        did_something = <optimized out>
        did_something = <optimized out>
#26 CRxAstfCore::_do_start (this=0x2363320)
    at ../../../../trex-core/src/stx/astf/trex_astf_rx_core.cpp:128
        dt = <optimized out>
       restart = true
        n_time = 8882.6185753949994
        node = 0x7fedac000b20
        __PRETTY_FUNCTION__ = "virtual int CRxAstfCore::_do_start()"
#27 0x000000000071f600 in CRxCore::start (this=0x2363320)
    at ../../../../trex-core/src/stx/common/trex_rx_core.cpp:519
No locals.
#28 0x0000000000512992 in CGlobalTRex::run_in_rx_core (this=0x11bdc80 <g_trex>)
    at ../../../../trex-core/src/main_dpdk.cpp:5322
        lp = <optimized out>
        param = <optimized out>
#29 0x0000000000537b8e in slave_one_lcore (dummy=<optimized out>)
    at ../../../../trex-core/src/main_dpdk.cpp:6242
        lpsock = <optimized out>
        phy_id = <optimized out>
#30 0x000000000094b370 in eal_thread_loop (arg=<optimized out>)
    at ../../../../trex-core/src/dpdk/lib/eal/linux/eal_thread.c:140
        f = <optimized out>
        fct_arg = <optimized out>
        c = 0 '\000'
        n = <optimized out>
        ret = <optimized out>
        lcore_id = <optimized out>
       thread_id = <optimized out>
        m2w = 14
        w2m = 25
        cpuset = "2", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#31 0x00007fedc4d856db in start_thread (arg=0x7fedc14ff700)
    at pthread_create.c:463
        pd = 0x7fedc14ff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140659127219968, 
                9053026567728966324, 140659127213568, 0, 0, 140724411082432, 
                -9045113518828246348, -9045121400399156556}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, 
            data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#32 0x00007fedc3b4c61f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

**Comment by hhaim** [comment]
```
https://github.com/cisco-system-traffic-generator/trex-core/issues/16 0x00000000006cce2a in Json::throwLogicError (msg=...)
at ../../../../trex-core/external_libs/json/jsoncpp.cpp:2683

```

It is as a rpc json corruption in CP 

@egwakim a few questions

1. is it a start command from the Console?
2. Is it happening with specific profile? can it be reproducible?

**Comment by jsmoon** [comment]
@hhaim
1. I don't think so. Although recently I observed the same issue twice, it could have happened to the older version also if the situation (response timeout) had been met.
2. I did not do that, but if I could make the response timeout situation, the crash would be reproduced.
