### ISSUE TITLE
Can someone tell me what I am missing? 

### ISSUE THREAD

**Issue by westlaker** [cisco-system-traffic-generator/trex-core#1070]
I found out that GUI client app does not support trex-core 2.88+ so I based on 2.87 and made it compiled but when I start trex, got the following error, appreciate any help here:

trex-2.87/trex-core/scripts$ sudo ./t-rex-64 -i -c 4
[sudo] password for ubuntu:
Starting Scapy server.... Scapy server failed to run
Output: b'Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)\n  File "/home/ubuntu/trex-2.87/trex-core/scripts/automation/trex_control_plane/interactive/trex/scapy_server/scapy_zmq_server.py",
line 8, in <module>    from ..stl.api import *  File "/home/ubuntu/trex-2.87/trex-
core/scripts/automation/trex_control_plane/interactive/trex/stl/api.py",    
line 7, in <module>    from .trex_stl_client import STLClient, PacketBuffer
File "/home/ubuntu/trex-2.87/trex-core/scripts/automation/trex_control_plane/interactive/trex/stl/trex_stl_client.py", 
line 8, in <module>    from ..utils import parsing_opts, text_tables\n  File "/home/ubuntu/trex-2.87/trex-core/scripts/automation/trex_control_plane/interactive/trex/utils/parsing_opts.py",
line 7, in <module>    from ..common.trex_vlan import VLAN      
File "/home/ubuntu/trex-2.87/trex-core/scripts/automation/trex_control_plane/interactive/trex/common/trex_vlan.py", 
line 8, in <module>    from scapy.layers.l2 import Dot1Q, Dot1AD  File "/home/ubuntu/trex-2.87/trex-core/scripts/external_libs/scapy-2.4.3/scapy/layers/l2.py",     
line 18, in <module>    from scapy.arch import get_if_addr, get_if_hwaddr      
File "/home/ubuntu/trex-2.87/trex-core/scripts/external_libs/scapy-2.4.3/scapy/arch/__init__.py", 
line 28, in <module>    from scapy.arch.bpf.core import get_if_raw_addr  File "/home/ubuntu/trex-2.87/trex-core/scripts/external_libs/scapy-2.4.3/scapy/arch/bpf/core.py",     
line 31, in <module>    LIBC = cdll.LoadLibrary(find_library("libc"))  File "/usr/lib/python3.10/ctypes/util.py",     
line 341, in find_library    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))  File "/usr/lib/python3.10/ctypes/util.py",     
line 147, in _findLib_gcc    if not _is_elf(file):  File "/usr/lib/python3.10/ctypes/util.py",     
line 99, in _is_elf    with open(filename, \'br\') as thefile:\nFileNotFoundError: [Errno 2] No such file or directory: b\'liblibc.a\''
Could not start scapy daemon server, which is needed by GUI to create packets.
If you don't need it, use --no-scapy-server flag.
ERROR encountered while configuring TRex system

**Comment by westlaker** [comment]
fixed
