### ISSUE TITLE
OSError installation Trex Centos

### ISSUE THREAD

**Issue by aaksenofontova** [cisco-system-traffic-generator/trex-core#113]
Hello, Trex-core Team!

I have an error when try to first start trex.

```
 sudo ./dpdk_setup_ports.py -s
Traceback (most recent call last):
  File "./dpdk_setup_ports.py", line 1332, in main
    dpdk_nic_bind.show_status()
  File "/opt/trex/v2.41/dpdk_nic_bind.py", line 603, in show_status
    get_nic_details()
  File "/opt/trex/v2.41/dpdk_nic_bind.py", line 281, in get_nic_details
    dev_lines = check_output(["lspci", "-Dvmmn"], universal_newlines = True).splitlines()
  File "/opt/trex/v2.41/dpdk_nic_bind.py", line 158, in check_output
    stderr=stderr, **kwargs).communicate()[0]
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

```
# hostnamectl
   Static hostname: hw-trex
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: ...
           Boot ID: ...
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.3.2.el7.x86_64
      Architecture: x86-64

```

What can i do to fix it?

Thanks,
Anna

**Comment by ybrustin** [comment]
Hi,

Please run:
sudo yum install pciutils

Thanks,
Yaroslav

**Comment by aaksenofontova** [comment]
Hi, Yaroslav

It works! 

Thanks,
Anna.
