### ISSUE TITLE
Unable to make multiple consequent start/stop traffic requests

### ISSUE THREAD

**Issue by zverevalexei** [cisco-system-traffic-generator/trex-core#16]
Hi @hhaim @imarom 

I'm finishing the apps (https://github.com/zverevalexei/killer-app-console, https://github.com/zverevalexei/trex-http-proxy), and I've just run into issue with multiple and subsequent start/stop requests: when I make them too fast, I keep getting a lot of errors in my console, like these:

Traceback (most recent call last):
  File "/home/trex/v2.03/http-proxy/trex-http-proxy/app.py", line 37, in start_traffic
    src_n=traffic_config['src_n']
  File "/home/trex/v2.03/http-proxy/trex-http-proxy/trex_api.py", line 116, in start_traffic
    client.connect()
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 1017, in wrap2
    ret = f(*args, **kwargs)
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 1380, in connect
    rc = self.__connect()
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 785, in __connect
    rc = self._transmit("api_sync", params = {'api_vers': self.api_vers}, api_class = None)
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 932, in _transmit
    return self.comm_link.transmit(method_name, params, api_class)
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 428, in transmit
    return self.rpc_link.invoke_rpc_method(method_name, params, api_class)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 120, in invoke_rpc_method
    id, msg = self.create_jsonrpc_v2(method_name, params, api_class)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 101, in create_jsonrpc_v2
    msg["id"] = next(self.id_gen)
ValueError: generator already executing

----

Unhandled exception in thread started by <function start_traffic at 0x7f5dc7b368c0>

----

Traceback (most recent call last):
  File "/home/trex/v2.03/http-proxy/trex-http-proxy/app.py", line 37, in start_traffic
    Unhandled exception in thread started by <function start_traffic at 0x7fe3da0228c0>
Traceback (most recent call last):
  File "/home/trex/v2.03/http-proxy/trex-http-proxy/app.py", line 37, in start_traffic
    src_n=traffic_config['src_n']
  File "/home/trex/v2.03/http-proxy/trex-http-proxy/trex_api.py", line 116, in start_traffic
    client.connect()
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 1017, in wrap2
    ret = f(*args, **kwargs)
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 1380, in connect
    src_n=traffic_config['src_n']
rc = self.__connect()
  File "/home/trex/v2.03/http-proxy/trex-http-proxy/trex_api.py", line 116, in start_traffic
    client.connect()
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 1017, in wrap2
      File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 795, in __connect
ret = f(*args, **kwargs)
    rc = self._transmit("get_version")
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 932, in _transmit
    return self.comm_link.transmit(method_name, params, api_class)
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 428, in transmit
    return self.rpc_link.invoke_rpc_method(method_name, params, api_class)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 122, in invoke_rpc_method
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 1380, in connect
        return self.send_msg(msg)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 159, in send_msg
    response = self.send_raw_msg(buffer)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 202, in send_raw_msg
rc = self.__connect()
    response = self.socket.recv()
  File "zmq/backend/cython/socket.pyx", line 631, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5772)
  File "zmq/backend/cython/socket.pyx", line 662, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5548)
  File "zmq/backend/cython/socket.pyx", line 96, in zmq.backend.cython.socket._check_closed (zmq/backend/cython/socket.c:1297)
zmq.error.  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 785, in __connect
ZMQError: Socket operation on non-socket
    rc = self._transmit("api_sync", params = {'api_vers': self.api_vers}, api_class = None)
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 932, in _transmit
    return self.comm_link.transmit(method_name, params, api_class)
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 428, in transmit
    return self.rpc_link.invoke_rpc_method(method_name, params, api_class)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 122, in invoke_rpc_method
    return self.send_msg(msg)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 159, in send_msg
    response = self.send_raw_msg(buffer)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 190, in send_raw_msg
    self.socket.send(msg)
  File "zmq/backend/cython/socket.pyx", line 574, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5434)
  File "zmq/backend/cython/socket.pyx", line 611, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5118)
  File "zmq/backend/cython/socket.pyx", line 96, in zmq.backend.cython.socket._check_closed (zmq/backend/cython/socket.c:1297)
zmq.error.ZMQError: Socket operation on non-socket

----

  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 428, in transmit
    return self.rpc_link.invoke_rpc_method(method_name, params, api_class)
Unhandled exception in thread started by <function start_traffic at 0x7f2d157308c0>
Traceback (most recent call last):
  File "/home/trex/v2.03/http-proxy/trex-http-proxy/app.py", line 37, in start_traffic
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 122, in invoke_rpc_method
    src_n=traffic_config['src_n']
  File "/home/trex/v2.03/http-proxy/trex-http-proxy/trex_api.py", line 116, in start_traffic
        client.connect()
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 1017, in wrap2
    ret = f(*args, **kwargs)
return self.send_msg(msg)
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 1380, in connect
    rc = self.__connect()
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 777, in __connect
    rc = self.comm_link.connect()
  File "trex_client/stl/trex_stl_lib/trex_stl_client.py", line 415, in connect
    return self.rpc_link.connect()
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 281, in connect
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 159, in send_msg
    rc = self.invoke_rpc_method('ping', api_class = None)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 122, in invoke_rpc_method
    return self.send_msg(msg)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 159, in send_msg
    response = self.send_raw_msg(buffer)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 202, in send_raw_msg
    response = self.socket.recv()
    response = self.send_raw_msg(buffer)
  File "zmq/backend/cython/socket.pyx", line 631, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5772)
  File "trex_client/stl/trex_stl_lib/trex_stl_jsonrpc_client.py", line 190, in send_raw_msg
    self.socket.send(msg)
  File "zmq/backend/cython/socket.pyx", line 665, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5572)
  File "zmq/backend/cython/socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1725)
  File "zmq/backend/cython/checkrc.pxd", line 18, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6184)
zmq.error.ContextTerminated: Context was terminated
  File "zmq/backend/cython/socket.pyx", line 574, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5434)
False
  File "zmq/backend/cython/socket.pyx", line 611, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5118)
  File "zmq/backend/cython/socket.pyx", line 96, in zmq.backend.cython.socket._check_closed (zmq/backend/cython/socket.c:1297)

----

many more...

**Comment by imarom** [comment]
Hi Alexei,

From the tracebacks it seems you are using multiple threads with the same client.

TRex Python API is not designed for multi-threading – you cannot do start/stop from parallel threads.

The error below:
ValueError: generator already executing

Is because a generator is called from multiple threads at a time.

Is your design a multi-threading application using the same client object ?

Thanks,
Itay

**Comment by imarom** [comment]
@zverevalexei 

from api.py:37:
 **thread.start_new_thread(start_traffic, (traffic_config,))**

here you start a new thread while passing start_traffic.
so i am assuming multiple threads will try to access the same client object.

Itay

**Comment by zverevalexei** [comment]
Hi Itay,

I used a separate thread to avoid blocked I/O. When I was starting TRex, I the I/O was blocked and I was not able to pass a message to frontend... In fact, I've seen a boolean parameter "async_start" here:
https://github.com/zverevalexei/trex-http-proxy/blob/33d87cafd00daa1ce84fa17dd9ced1278fd8bd9e/t_rex_stateless.py (line 237)

Seems like it does the same job? I'll try it out in a while.

**Comment by imarom** [comment]
@zverevalexei @ybrustin 
I am adding Yaroslav to this thread as I think he is the owner of t_rex_stateless.py in our project.

On a quick look, yes.
it seems like async_start will exit without disabling the traffic and will not block until traffic is done.

But i am not sure this is what you need.
the pointer you have given is actually a full session of a burst.
it will connect to a client, start traffic, block and disconnect.

But don't you actually need a state preserving API ?
Why would you connect/disconnect per transaction ?

Yaroslav,
Please take a look and advise on the right approach.
I am not too familair with this proxy.

Thanks,
Itay

**Comment by zverevalexei** [comment]
@imarom yes I do :) 

I sent the old version of that file, here's a new one https://github.com/zverevalexei/trex-http-proxy/blob/master/trex_api.py (based on Yaroslav's code and one the examples). I made it more flexible, but didn't use "async_start" option.

**Comment by zverevalexei** [comment]
Hey... I seem to have sorted that out: just removed anything that had to do with "thread" module and it worked out. The weird thing is it used to block I/O before, but I may have had other factors that had influenced that. 

Thanks.
