### ISSUE TITLE
Scapy library update

### ISSUE THREAD

**Issue by EgorBlagov** [cisco-system-traffic-generator/trex-core#179]
Hi,

The users of GUI are facing the issue while creating IGMPv3 packets using packet editor, that depends on Scapy server and scapy itself. After some debugging, I found issue that is reproducible with Scapy v2.3.1 (which TRex currently use) and not reproducible on Scapy v2.4.0 (latest).

here are the details:
```

# call with scapy 2.4.0 works fine
from scapy.contrib.igmpv3 import IGMPv3gr

pkt = IGMPv3gr(srcaddrs=['1.2.3.4'])
IGMPv3gr(bytes(pkt)).show()
print('all good')

# output:
'''

###[ IGMPv3gr ]### 
  rtype     = Mode Is Include
  auxdlen   = 0
  numsrc    = 1
  maddr     = 0.0.0.0
  srcaddrs  = [1.2.3.4]

all good

'''


# another call with scapy form TRex (2.3.1)

from trex.stl.api import scapy
from scapy.contrib.igmpv3 import IGMPv3gr
pkt = IGMPv3gr(srcaddrs=['1.2.3.4'])
IGMPv3gr(bytes(pkt)).show()
print('all good')

# output:
'''

IGMPv3  is still under development - Nov 2010
Traceback (most recent call last):
  File "/home/egor/Desktop/trex/trex-core/scripts/automation/trex_control_plane/interactive/scapy_test.py", line 29, in <module>
    IGMPv3gr(bytes(pkt)).show()
  File "/home/egor/Desktop/trex/trex-core/scripts/external_libs/scapy-2.3.1/python3/scapy/base_classes.py", line 199, in __call__
    i.__init__(*args, **kargs)
  File "/home/egor/Desktop/trex/trex-core/scripts/external_libs/scapy-2.3.1/python3/scapy/packet.py", line 97, in __init__
    self.dissect(_pkt)
  File "/home/egor/Desktop/trex/trex-core/scripts/external_libs/scapy-2.3.1/python3/scapy/packet.py", line 719, in dissect
    s = self.do_dissect(s)
  File "/home/egor/Desktop/trex/trex-core/scripts/external_libs/scapy-2.3.1/python3/scapy/packet.py", line 684, in do_dissect
    s,fval = f.getfield(self, s)
  File "/home/egor/Desktop/trex/trex-core/scripts/external_libs/scapy-2.3.1/python3/scapy/fields.py", line 604, in getfield
    l = self.length_from(pkt)
TypeError: 'str' object is not callable

'''
```

This operation: converting to bytes and parsing bytes again with Scapy is very main.

The question is: How should we fix that issue? Is it possible to update Scapy package in TRex sources? Or we should find particular fix of that IGMPv3 issue, and edit scapy library copy by ourselves?

Thanks & regards
Egor.

**Comment by hhaim** [comment]
In general it is better to update the protocol itself (both in python 2.7 and python 3 lib)
regarding this IGMPv3, I remember that @ybrustin  handled this in the past. need to check with him
