### ISSUE TITLE
NameError: 'tunables' is not defined 

### ISSUE THREAD

**Issue by KunwarAkanksha** [cisco-system-traffic-generator/trex-core#190]
Please help me with this.
After starting my trex server with sudo ./t-rex-64 -i , I am opening ./trex-console through other window on which I am getiing same error for any file : 

trex>start -f stl/udp_1pkt_simple.py -m 10mbps -a

----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/trex-core/scripts/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 937, in <module>
    main()
  File "/opt/trex-core/scripts/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 926, in main
    console.start()
  File "/opt/trex-core/scripts/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 643, in start
    self.cmdloop()
  File "/usr/lib64/python2.7/cmd.py", line 141, in cmdloop
    line = self.precmd(line)
  File "/opt/trex-core/scripts/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 293, in precmd
    stop = self.onecmd(line)
  File "/usr/lib64/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/opt/trex-core/scripts/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 125, in wrap2
    rc = f(*args)
  File "/opt/trex-core/scripts/automation/trex_control_plane/interactive/trex/stl/trex_stl_client.py", line 1720, in start_line
    direction = tunables.get('direction', port % 2),
NameError: global name 'tunables' is not defined
----------------------------------------------------------------------------------------------------------------------------------------------
also my /tmp folder do not contain trex.log, although I can see the history of trex-console in /tmp/trex/console

**Comment by hhaim** [comment]
Resolved in V2.53
