### ISSUE TITLE
trex server crashed , Unable to add more than 700 streams

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#282]
```
   m_PyList = source_mac_list;
    i_PyList = source_ip_list;

    streams_all = []
    for i in range(len(m_PyList)):
        packet = (Ether(dst=dst_mac,src=m_PyList[i]) /
                      Dot1Q(vlan=vlan_id) /
                      IP(src=source_ip_list[i],dst=dst_ip) /
                      UDP(sport=1025,dport=1025) /
                      Raw(load='\x00' * size) /
                      Raw(load='\x00' * 8))    
        vm = STLVM()
        s1 = STLStream(packet = STLPktBuilder(pkt = packet, vm = vm),
                               mac_src_override_by_pkt = True,
                               mac_dst_override_mode = 1,
                               mode = STLTXCont())
        streams_all.append(s1)
    try:
        c.add_streams(streams = streams_all ,ports = [tx_port]) 

    except:
        #Disable latency if NIC does not support requested stream type
        print "##### FAILED to add streams #####" 


```

crash 

```

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./_t-rex-64 -i --stl --allow-coredump'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f258cb39c37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f258cb39c37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f258cb3d028 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f258e7f4c55 in CGlobalTRex::abort_gracefully (this=<optimized out>, on_stdout=..., on_publisher=...) at ../../src/main_dpdk.cpp:3319
#3  0x00007f258e7f4cc6 in abort_gracefully (on_stdout=..., on_publisher=...) at ../../src/main_dpdk.cpp:5804
#4  0x00007f258e805c7e in _callstack_signal_handler (signr=<optimized out>, info=<optimized out>, secret=<optimized out>) at ../../src/trex_watchdog.cpp:126
#5  <signal handler called>
#6  0x00007f258cb821b6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007f258e936b01 in releaseStringValue (value=<optimized out>) at ../../external_libs/json/jsoncpp.cpp:2642
#8  ~CZString (this=0x7f2580018f70, __in_chrg=<optimized out>) at ../../external_libs/json/jsoncpp.cpp:2755
#9  ~pair (this=0x7f2580018f70, __in_chrg=<optimized out>) at /usr/local/gcc-6.2/include/c++/6.2.0/bits/stl_pair.h:147
#10 destroy<std::pair<Json::Value::CZString const, Json::Value> > (this=<optimized out>, __p=<optimized out>)
    at /usr/local/gcc-6.2/include/c++/6.2.0/ext/new_allocator.h:124
#11 destroy<std::pair<Json::Value::CZString const, Json::Value> > (__a=..., __p=<optimized out>) at /usr/local/gcc-6.2/include/c++/6.2.0/bits/alloc_traits.h:467
#12 _M_destroy_node (this=0x7f2580879420, __p=0x7f2580018f50) at /usr/local/gcc-6.2/include/c++/6.2.0/bits/stl_tree.h:567
#13 _M_drop_node (__p=0x7f2580018f50, this=0x7f2580879420) at /usr/local/gcc-6.2/include/c++/6.2.0/bits/stl_tree.h:575
#14 std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value>)
    at /usr/local/gcc-6.2/include/c++/6.2.0/bits/stl_tree.h:1615
#15 0x00007f258e9284a4 in ~_Rb_tree (this=0x7f2580879420, __in_chrg=<optimized out>) at /usr/local/gcc-6.2/include/c++/6.2.0/bits/stl_tree.h:873
#16 ~map (this=0x7f2580879420, __in_chrg=<optimized out>) at /usr/local/gcc-6.2/include/c++/6.2.0/bits/stl_map.h:96
#17 Json::Value::~Value (this=0x7f258079c9d0, __in_chrg=<optimized out>) at ../../external_libs/json/jsoncpp.cpp:2979
#18 0x00007f258e936a92 in ~pair (this=0x7f258079c9c0, __in_chrg=<optimized out>) at /usr/local/gcc-6.2/include/c++/6.2.0/bits/stl_pair.h:147
#19 destroy<std::pair<Json::Value::CZString const, Json::Value> > (this=<optimized out>, __p=<optimized out>)

```

**Comment by hhaim** [comment]
```
import stl_path
from trex.stl.api import *

import time

def get_mac (prefix,index):
    mac="{}:{:02x}:{:02x}".format(prefix,(index>>8)&0xff,(index&0xff))
    return (mac)

def get_ipv4 (prefix,index):
    ipv4="{}.{:d}.{:d}".format(prefix,(index>>8)&0xff,(index&0xff))
    return(ipv4)



def build_network (l,size):
    MAC_PREFIX="00:01:02:03"
    for i in range(size):
        mac = get_mac (MAC_PREFIX,i+257+1)
        l.append(mac)

def build_network_ip (l,size):
    IPV4_PREFIX="1.1"
    for i in range(size):
        ipv4  =get_ipv4 (IPV4_PREFIX,259+i)
        l.append(ipv4)


def simple_burst (port_a, port_b, pkt_size, burst_size, rate):

    # create client
    c = STLClient(server = "server")
    passed = True
    
    try:
        m_PyList=[]
        i_PyList=[]
        size = 10000
        pkt_size = 10
        build_network (m_PyList,size) 
        build_network_ip (i_PyList,size)
        dst_mac = "00:01:01:01:01:01"
        vlan_id = 7
        dst_ip = "10.0.0.2"
        streams_all = []
        for i in range(len(m_PyList)):
            packet = (Ether(dst=dst_mac,src=m_PyList[i]) /
                          Dot1Q(vlan=vlan_id) /
                          IP(src=i_PyList[i],dst=dst_ip) /
                          UDP(sport=1025,dport=1025) /
                          Raw(load='\x00' * pkt_size) /
                          Raw(load='\x00' * 8))    
            vm = STLVM()
            s1 = STLStream(packet = STLPktBuilder(pkt = packet, vm = vm),
                                   mac_src_override_by_pkt = True,
                                   mac_dst_override_mode = 1,
                                   mode = STLTXCont())
            streams_all.append(s1)




        # connect to server
        c.connect()

        # prepare our ports
        c.reset(ports = [0, 1])

        # add both streams to ports
        stream_ids = c.add_streams(streams = streams_all, ports = [0])

        # run 5 times
        c.clear_stats()
        c.start(ports = [0], mult = rate, duration = 1)
        c.wait_on_traffic(ports = [0])
        c.reset(ports = [0, 1])

        stats = c.get_stats()
        ipackets  = stats['total']['ipackets']

        print("Test iteration {0} - Packets Received: {1} ".format(0, ipackets))
            # two streams X 2 ports
        if (ipackets != (burst_size * 2 * 2)):
                passed = False

    except STLError as e:
        passed = False
        print(e)

    finally:
        c.disconnect()

    if c.get_warnings():
            print("\n\n*** test had warnings ****\n\n")
            for w in c.get_warnings():
                print(w)

    if passed and not c.get_warnings():
        print("\nTest has passed :-)\n")
    else:
        print("\nTest has failed :-(\n")


# run the tests
simple_burst(0, 1, 256, 50000, "10%")
#print("hey");

```

I'm using this with 10,000 streams without any issue. 
Could you test it on your setup?
