### ISSUE TITLE
Server has been shutdown - cause: 'WATCHDOG: task 'STL RX CORE' has not responded for more than 1.00664 seconds - timeout is 1 seconds

### ISSUE THREAD

**Issue by wanghekai** [cisco-system-traffic-generator/trex-core#395]
Version : v2.59 
I have a problem when i use trex test the performance , The error message below

TRex status is: False
TRex status is: {'state': TRexStatus.Idle, 'verbose': 'TRex is Idle'}
After Starting, TRex status is: True,{'state': TRexStatus.Running, 'verbose': 'TRex is Running'}
Is TRex running? True,{'state': TRexStatus.Running, 'verbose': 'TRex is Running'}
After started Trex server 
Start check port stats 
ports [0] Test result 
{
    "ver_id": {
        "1": 0
    },
    "flow_stats": {
        "global": {
            "rx_err": {
                "0": 0,
                "1": 0
            },
            "tx_err": {
                "0": 0,
                "1": 0
            }
        },
        "1": {
            "rx_pkts": {
                "0": 10000,
                "1": 0,
                "total": 10000
            },
            "rx_bytes": {
                "0": "N/A",
                "1": "N/A",
                "total": "N/A"
            },
            "tx_pkts": {
                "0": 10000,
                "1": 0,
                "total": 10000
            },
            "tx_bytes": {
                "0": 680000,
                "1": 0,
                "total": 680000
            },
            "rx_bps": {
                "0": 0.0,
                "1": 0.0,
                "total": 0.0
            },
            "rx_pps": {
                "0": 0.0,
                "1": 0.0,
                "total": 0.0
            },
            "tx_bps": {
                "0": 0.0,
                "1": 0.0,
                "total": 0.0
            },
            "tx_pps": {
                "0": 0.0,
                "1": 0.0,
                "total": 0.0
            },
            "rx_bps_l1": {
                "0": 0.0,
                "1": 0.0,
                "total": 0.0
            },
            "tx_bps_l1": {
                "0": 0.0,
                "1": 0.0,
                "total": 0.0
            }
        }
    }
}
and Then ,I began performance test .
First 
start 6.0 mpps throughput begin 
2019-12-19 05:59:20 - [server][warning]  - Server has been shutdown - cause: 'WATCHDOG: task 'STL RX CORE' has not responded for more than 1.00664 seconds - timeout is 1 seconds

*** traceback follows ***

1       0x55b94703939a ./_t-rex-64(+0x17339a) [0x55b94703939a]
2       0x7f1b51b48630 /lib64/libpthread.so.0(+0xf630) [0x7f1b51b48630]
3       0x55b94719a533 CRxCore::work_tick() + 147
4       0x55b947199b13 CRxCore::_do_start() + 99
5       0x55b947199e08 CRxCore::start() + 392
6       0x55b94702486f CGlobalTRex::run_in_rx_core() + 95
7       0x55b94702c53c ./_t-rex-64(+0x16653c) [0x55b94702c53c]
8       0x55b9472ca6ed eal_thread_loop + 477
9       0x7f1b51b40ea5 /lib64/libpthread.so.0(+0x7ea5) [0x7f1b51b40ea5]
10      0x7f1b50bb58cd clone + 109

*** addr2line information follows ***

??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0

'
Traceback (most recent call last):
  File "./trex_sport.py", line 247, in <module>
    stat = repeat_through_put(c,try_vlaue,duration,real_ports,s1)
  File "./trex_sport.py", line 79, in repeat_through_put
    c.wait_on_traffic(ports = ports)
  File "/v2.59/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 51, in wrap2
    ret = f(*args, **kwargs)
  File "v2.59/automation/trex_control_plane/interactive/trex/stl/trex_stl_client.py", line 868, in wait_on_traffic
    TRexClient.wait_on_traffic(self, ports, timeout)
  File "/v2.59/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 51, in wrap2
    ret = f(*args, **kwargs)
  File "v2.59/automation/trex_control_plane/interactive/trex/common/trex_client.py", line 1909, in wait_on_traffic
    while set(self.get_active_ports()).intersection(ports):
  File "/v2.59/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 45, in wrap2
    raise TRexError("'{0}' - connection to the server had been lost: '{1}'".format(func_name, client.conn.get_disconnection_cause()))
trex.common.trex_exceptions.TRexError: 'get_active_ports' - connection to the server had been lost: 'WATCHDOG: task 'STL RX CORE' has not responded for more than 1.00664 seconds - timeout is 1 seconds

*** traceback follows ***

1       0x55b94703939a ./_t-rex-64(+0x17339a) [0x55b94703939a]
2       0x7f1b51b48630 /lib64/libpthread.so.0(+0xf630) [0x7f1b51b48630]
3       0x55b94719a533 CRxCore::work_tick() + 147
4       0x55b947199b13 CRxCore::_do_start() + 99
5       0x55b947199e08 CRxCore::start() + 392
6       0x55b94702486f CGlobalTRex::run_in_rx_core() + 95
7       0x55b94702c53c ./_t-rex-64(+0x16653c) [0x55b94702c53c]
8       0x55b9472ca6ed eal_thread_loop + 477
9       0x7f1b51b40ea5 /lib64/libpthread.so.0(+0x7ea5) [0x7f1b51b40ea5]
10      0x7f1b50bb58cd clone + 109

*** addr2line information follows ***

??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0
??:0

'

**Comment by egwakim** [comment]
Hi,
You are using quite old version of TRex, please try to use the latest version of TRex.
Some watchdog fix have been done.
