### ISSUE TITLE
trex_emu_conversions.py missing listify module

### ISSUE THREAD

**Issue by Opiekelly** [cisco-system-traffic-generator/trex-core#469]
When looking at EMU client information with tpids.   

It will fail as listify module is not imported in trex_emu_conversions.py
from ..common.trex_types import listify 

trex>emu_show_client_info -p 1 --vlan 121 --tpid 0x8100 --mac 00:00:00:70:00:01

Unloading plugin: emu
Disconnecting from server at 'osp1':'4510'                   [SUCCESS]

[SUCCESS]

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/brenkell/trex/v2.77/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 997, in <module>
    main()
  File "/home/brenkell/trex/v2.77/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 993, in main
    run_console(client, logger, options)
  File "/home/brenkell/trex/v2.77/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 892, in run_console
    console.start()
  File "/home/brenkell/trex/v2.77/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 668, in start
    self.cmdloop()
  File "/usr/local/lib/python3.8/cmd.py", line 137, in cmdloop
    line = self.precmd(line)
  File "/home/brenkell/trex/v2.77/automation/trex_control_plane/interactive/trex/console/trex_console.py", line 316, in precmd
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/brenkell/trex/v2.77/automation/trex_control_plane/interactive/trex/common/trex_api_annotators.py", line 189, in wrap2
    rc = f(*args)
  File "/home/brenkell/trex/v2.77/automation/trex_control_plane/interactive/trex/emu/trex_emu_client.py", line 1420, in show_client_info_line
    c_info = self.get_info_client(conv_ns(opts.port, opts.vlan, opts.tpid), [opts.mac])
  File "/home/brenkell/trex/v2.77/automation/trex_control_plane/interactive/trex/emu/trex_emu_conversions.py", line 208, in conv_ns
    tpids = [int(t, base = 16) for t in listify(tpids)]
NameError: name 'listify' is not defined

**Comment by elados93** [comment]
Already fixed at: fa6e52acc7c63bda7853c6e05b550368b6cf7b2c
I'm closing the issue
