### ISSUE TITLE
dpdk_setup_port.py cannot create config file by command line args.

### ISSUE THREAD

**Issue by jsmoon** [cisco-system-traffic-generator/trex-core#522]
Hi @hhaim,
I think 2855e1b is causing following issue. Would you fix this?
```
$ sudo ./dpdk_setup_ports.py -o trex_cfg.yaml --ips 1.1.1.1 2.2.2.2 --def-gws 2.2.2.2 1.1.1.1 -c 00:08.0 00:09.0
Traceback (most recent call last):
  File "./dpdk_setup_ports.py", line 1638, in main
    obj.do_create();
  File "./dpdk_setup_ports.py", line 1279, in do_create
    prefix = map_driver.args.prefix, zmq_rpc_port = map_driver.args.zmq_rpc_port, zmq_pub_port = map_driver.args.zmq_pub_port)
  File "./dpdk_setup_ports.py", line 114, in __init__
    Device_str = self._verify_devices_same_type(self.interfaces)
  File "./dpdk_setup_ports.py", line 179, in _verify_devices_same_type
    TrexDrv = interfaces_list[0]['TRex_Driver']
KeyError: 'TRex_Driver'
```

**Comment by hhaim** [comment]
@jsmoon yes, will be fixed soon
