### ISSUE TITLE
trex with mlx5 driver crash on specific configuration  

### ISSUE THREAD

**Issue by hhaim** [cisco-system-traffic-generator/trex-core#746]
```
sudo ./t-rex-64-debug-gdb -i -c 2 --cfg /etc/trex_cfg_linux_stack.yaml
```
### Config file generated by dpdk_setup_ports.py ###

- port_limit: 2
  version: 2
  interfaces: ['04:00.0', '04:00.1']
  stack: linux_based
  memory:
      dp_flows: 10000000
      mbuf_1025: 16380
      mbuf_128: 16380
      mbuf_2048: 1380
      mbuf_256: 16380
      mbuf_512: 16380
      mbuf_64: 32760
      traffic_mbuf_1025: 16380
      traffic_mbuf_128: 16380
      traffic_mbuf_2048: 16380
      traffic_mbuf_256: 1380
      traffic_mbuf_512: 16380
      traffic_mbuf_64: 32760

  port_info:
      - ip: 1.1.1.1
        default_gw: 2.2.2.2
      - ip: 2.2.2.2
        default_gw: 1.1.1.1

  platform:
      master_thread_id: 0
      latency_thread_id: 14
      dual_if:
        - socket: 0
          threads: [1,2,3,4,5,6,7,8,9,10,11,12,13]
```

```
Detaching after fork from child process 11014]
terminate called after throwing an instance of 'TrexException'
  what():  Could not find program "ip", which is required for Linux-based stack
Cmd: ip -V
Output: 

Program received signal SIGABRT, Aborted.
0x00007ffff649b387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-317.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libibverbs-52mlnx1-1.53100.x86_64 libnl3-3.2.28-4.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00007ffff649b387 in raise () from /lib64/libc.so.6
#1  0x00007ffff649ca78 in abort () from /lib64/libc.so.6
#2  0x00007ffff6ddc6e5 in __gnu_cxx::__verbose_terminate_handler() () from so/x86_64/libstdc++.so.6
#3  0x00007ffff6dda4c6 in ?? () from so/x86_64/libstdc++.so.6
#4  0x00007ffff6dda511 in std::terminate() () from so/x86_64/libstdc++.so.6
#5  0x00007ffff6dda753 in __cxa_throw () from so/x86_64/libstdc++.so.6
#6  0x0000555555cfad25 in popen_general (cmd=..., err=..., throw_exception=true, output=...)
    at ../../src/stx/common/trex_stack_linux_based.cpp:1259
#7  0x0000555555cfaf73 in popen_with_err (cmd=..., err=...) at ../../src/stx/common/trex_stack_linux_based.cpp:1270
#8  0x0000555555cfa5ce in verify_programs () at ../../src/stx/common/trex_stack_linux_based.cpp:1232
#9  0x0000555555cee481 in CStackLinuxBased::CStackLinuxBased (this=0x55555a7701c0, api=0x55555a770198, 
    ignore_stats=0x55555a770168) at ../../src/stx/common/trex_stack_linux_based.cpp:70
#10 0x0000555555ccb996 in CStackFactory::create (type_name=..., api=0x55555a770198, ignore_stats=0x55555a770168)
    at ../../src/stx/common/trex_stack_base.cpp:942
#11 0x0000555555cbcd4f in RXPortManager::create_async (this=0x55555a7693a0, port_id=1, rx_core=0x55555a742c90, io=
    0x555557c49b68 <g_trex+5817512>, rfc2544=0x55555a742e78, err_cntrs=0x55555a742e20, cpu_util=0x55555a742d90)
    at ../../src/stx/common/trex_rx_port_mngr.cpp:490
#12 0x0000555555ca44c0 in CRxCore::create (this=0x55555a742c90, cfg=...) at ../../src/stx/common/trex_rx_core.cpp:125
#13 0x0000555555d1fdf6 in TrexStateless::TrexStateless (this=0x55555a73f360, cfg=...) at ../../src/stx/stl/trex_stl.cpp:184
#14 0x0000555555ad6874 in CGlobalTRex::init_stl (this=0x5555576bd6c0 <g_trex>) at ../../src/main_dpdk.cpp:3948
#15 0x0000555555ad6497 in CGlobalTRex::Create (this=0x5555576bd6c0 <g_trex>) at ../../src/main_dpdk.cpp:3870
#16 0x0000555555ae1038 in main_test (argc=8, argv=0x7fffffffe438) at ../../src/main_dpdk.cpp:6764
#17 0x0000555555ade482 in main (argc=8, argv=0x7fffffffe438) at ../../src/main_dpdk.cpp:6090
(gdb) quit
A debugging session is active.

        Inferior 1 [process 11000] will be killed.

```

**Comment by hhaim** [comment]
the reason is this function 

```
void popen_general(const string &cmd, const string &err, bool throw_exception, string &output) {
    string cmd_with_redirect = cmd + " 2>&1";
    debug("stack going to run: " + cmd);
    FILE *fstream = popen(cmd_with_redirect.c_str(), "r");
    if ( fstream == nullptr && throw_exception ) {
        throw TrexException(err + " (popen could not allocate memory to execute cmd: " + cmd + ").");
    }
    char buffer[1024];
    while ( fgets(buffer, sizeof(buffer), fstream) != nullptr ) {
        output += buffer;
    }
    int ret = pclose(fstream);
    if ( ret && throw_exception ) {
        if ( WIFEXITED(ret) ) {
            throw TrexException(err + "\nCmd: " + cmd + "\nReturn code: " + to_string(WEXITSTATUS(ret)) + "\nOutput: " + output + "\n");
        } else {
            throw TrexException(err + "\nCmd: " + cmd + "\nOutput: " + output + "\n");
        }
    }
}

```

That call to fork and because the process is pretty heavy (with mlx5 driver) and return with an error (due to fork issue)
better to replace it with either smaller process that communicates with RPC or with this trick 
https://blog.famzah.net/2009/11/20/a-much-faster-popen-and-system-implementation-for-linux/

**Comment by hhaim** [comment]
I've looked into this more, the vfork library has a bug that crash in case of reading the fd. we should create a small python process that get the command from share-memory fd and give back the results on this file

**Comment by hhaim** [comment]
duplicate #722 , same issue fork takes very high resource
