### ISSUE TITLE
error when running t-rex-64

### ISSUE THREAD

**Issue by kaiwangsim** [cisco-system-traffic-generator/trex-core#835]
Hi, I'm running into below error when I tried to start trex, is there anything wrong? host machine is ubuntu 20.04

root@wang:/opt/trex/v2.97# sudo ./t-rex-64 -i
WARNING: tried to configure 2048 hugepages for socket 0, but result is: 1592
Starting Scapy server..... Scapy server is started
Trying to bind to vfio-pci ...
Trying to compile and bind to igb_uio ...
ERROR: We don't have precompiled igb_uio.ko module for your kernel version.
Will try compiling automatically...
Traceback (most recent call last):
  File "./dpdk_setup_ports.py", line 1738, in main
    ret = obj.do_run()
  File "./dpdk_setup_ports.py", line 1075, in do_run
    compile_and_load_igb_uio()
  File "./dpdk_setup_ports.py", line 352, in compile_and_load_igb_uio
    subprocess.check_output('make', cwd = build_src_path, stderr = subprocess.STDOUT, universal_newlines = True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'make'
ERROR encountered while configuring TRex system

**Comment by hhaim** [comment]
@kaiwangsim install `make` and kernel header to build the kernel module
